name: Complie & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install boost
      run: sudo apt-get update && sudo apt-get install -yq libboost1.65-dev
    - name: Compile
      run: make
    - name: Run e2e tests
      run: ./run-tests.sh
    - name: Unit Tests
      run: make test
